# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-04 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat_1', models.PositiveIntegerField()),
                ('lon_1', models.PositiveIntegerField()),
                ('lat_2', models.PositiveIntegerField()),
                ('lon_2', models.PositiveIntegerField()),
                ('lat_3', models.PositiveIntegerField()),
                ('lon_3', models.PositiveIntegerField()),
                ('lat_4', models.PositiveIntegerField()),
                ('lon_4', models.PositiveIntegerField()),
            ],
        ),
    ]
