# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-04 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='shape_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat_1', models.IntegerField()),
                ('lon_1', models.IntegerField()),
                ('lat_2', models.IntegerField()),
                ('lon_2', models.IntegerField()),
                ('lat_3', models.IntegerField()),
                ('lon_3', models.IntegerField()),
                ('lat_4', models.IntegerField()),
                ('lon_4', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='map',
        ),
    ]
