# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-04 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20200205_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shape_data',
            name='lat_1',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='shape_data',
            name='lat_2',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='shape_data',
            name='lat_3',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='shape_data',
            name='lat_4',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='shape_data',
            name='lon_1',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='shape_data',
            name='lon_2',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='shape_data',
            name='lon_3',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='shape_data',
            name='lon_4',
            field=models.FloatField(),
        ),
    ]
