# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-04 19:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_auto_20200205_0045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shape_data',
            old_name='lat_1',
            new_name='east',
        ),
        migrations.RenameField(
            model_name='shape_data',
            old_name='lat_2',
            new_name='north',
        ),
        migrations.RenameField(
            model_name='shape_data',
            old_name='lat_3',
            new_name='south',
        ),
        migrations.RenameField(
            model_name='shape_data',
            old_name='lat_4',
            new_name='west',
        ),
        migrations.RemoveField(
            model_name='shape_data',
            name='lon_1',
        ),
        migrations.RemoveField(
            model_name='shape_data',
            name='lon_2',
        ),
        migrations.RemoveField(
            model_name='shape_data',
            name='lon_3',
        ),
        migrations.RemoveField(
            model_name='shape_data',
            name='lon_4',
        ),
    ]
